name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm install
      - name: Install dependencies (backend)
        run: |
          cd backend/server
          npm install --force
      - name: Run backend tests
        run: |
          cd backend/server
          npm test

  test_frontend:
    needs: test_backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Run frontend tests
        run: |
          cd frontend
          npm test

  build:
    needs: [test_backend, test_frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Build frontend
        run: |
          cd frontend
          npm install react-scripts
          npm run build
      - name: Build backend
        run: |
          cd backend/server
          npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-files
          path: |
            frontend/build
            backend/server/dist
